# https://gist.github.com/jbfriedrich/49b186473486ac72c4fe194af01288be?permalink_comment_id=4775455
# /etc/nsmb.conf

[default] 
protocol_vers_map=2 
streams=no 
soft=yes 
dir_cache_off=yes 
notify_off=yes 
signing_required=no 
