# Mac-like keyboard shortcuts for a windows keyboard
# Place in /etc/keyd/default.conf

[ids]
*

[main]
# Use meta as option key and alt as command key
leftmeta = layer(opt)
leftalt = layer(cmd)

# Option layer, inherits from "alt" layer

[opt:A]
# Disable alt+tab so it doesn't conflict with "app_switch"
tab = noop

# Option text navigation
right = C-right
left = C-left
backspace = C-backspace

# Command layer, inherits from "control" layer

[cmd:C]
# Essential shortcuts, rest are inherited from "control" layer
c = C-insert
v = S-insert
x = S-delete

# Tab navigation
1 = A-1
2 = A-2
3 = A-3
4 = A-4
5 = A-5
6 = A-6
7 = A-7
8 = A-8
9 = A-9

# Command text navigation
left = home
right = end
up = C-home
down = C-end

# As soon as tab is pressed, but not released, we switch to the
# "app_switch" layer and send a "M-tab" key tap before entering it.
tab = swapm(app_switch, M-tab)

# Switch to next window in the application group (default alt+f6)
` = A-f6

# App switch layer

[app_switch:M]
tab = M-tab
right = M-tab
left = M-S-tab
