# Mac: colors in terminal
# export TERM="xterm-256color" CLICOLOR=1

export EDITOR="zed --wait"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export GOPATH=$HOME/go
export GEM_HOME=$HOME/.gems
export GEM_PATH=$GEM_HOME
export PATH=$GEM_HOME/bin:$GOPATH/bin:$HOME/.local/bin:/usr/local/sbin:$PATH

export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt incappendhistory

# Linux: homebrew
# eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Linux: alt-arrow navigation and delete key in terminal
# bindkey "\e[1;5C" forward-word
# bindkey "\e[1;5D" backward-word
# bindkey "\e[3~" delete-char

bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

autoload -Uz add-zsh-hook vcs_info
autoload -Uz compinit && compinit
setopt prompt_subst
add-zsh-hook precmd vcs_info

PROMPT='%F{green}%(4~|…/%3~|%~)%f ${vcs_info_msg_0_}'

zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"
zstyle ':completion:*' menu select
zstyle ':completion:*' complete-options true
zstyle ':completion:*' file-sort modification
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:git:*' formats '%F{blue}(%b%u%c)%f '
zstyle ':vcs_info:git:*' actionformats '(%b|%a%u%c)'

# brew install mcfly
eval "$(mcfly init zsh)"

# Aliases
alias ll="ls -alF"
alias server="python3 -m http.server"

# Editor shorthand
function z() {
  zed -w $1
}

# Tab title
function precmd() {
  print -Pn "\e]2;$(pwd | xargs basename)\a"
}

# zsh-autosuggestions https://github.com/zsh-users/zsh-autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
