export EDITOR="zed --wait"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export GEM_HOME=$HOME/.gems
export GEM_PATH=$GEM_HOME
export GOPATH=$HOME/.local/go
export LOCAL_PATH=$HOME/.local/bin
# Mac, intel
# export MACPORTS_PATH=/opt/local/bin:/opt/local/sbin
export HERD_LITE_PATH=$HOME/.config/herd-lite/bin
export PHP_INI_SCAN_DIR=$HOME/.config/herd-lite/bin:$PHP_INI_SCAN_DIR
# Mac, intel
# export PATH=$GEM_HOME/bin:$GOPATH/bin:$LOCAL_PATH:$MACPORTS_PATH:$HERD_LITE_PATH:$PATH
# Mac, silicon
export PATH=$GEM_HOME/bin:$GOPATH/bin:$LOCAL_PATH:$HERD_LITE_PATH:$PATH

export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt incappendhistory

# Mac, silicon
eval "$(/opt/homebrew/bin/brew shellenv)"
# Linux
# eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Linux: alt-arrow navigation and delete key in terminal
# bindkey "\e[1;5C" forward-word
# bindkey "\e[1;5D" backward-word
# bindkey "\e[3~" delete-char

bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

autoload -Uz add-zsh-hook vcs_info
autoload -Uz compinit && compinit
setopt prompt_subst
add-zsh-hook precmd vcs_info

PROMPT='%F{green}%(4~|…/%3~|%~)%f ${vcs_info_msg_0_}'

zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"
zstyle ':completion:*' menu select
zstyle ':completion:*' complete-options true
zstyle ':completion:*' file-sort modification
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:git:*' formats '%F{blue}(%b%u%c)%f '
zstyle ':vcs_info:git:*' actionformats '(%b|%a%u%c)'

# Tab title
function precmd() {
  print -Pn "\e]2;$(pwd | xargs basename)\a"
}

# Aliases
alias ll="ls -alF"
alias server="python3 -m http.server"
alias z="zed"

# McFly · https://github.com/cantino/mcfly
eval "$(mcfly init zsh)"                                                        # Homebrew
# source "/opt/local/share/mcfly/mcfly.zsh"                                     # MacPorts

# zsh-autosuggestions · https://github.com/zsh-users/zsh-autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh       # Homebrew
# source "/opt/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh"         # MacPorts

# chruby · https://github.com/postmodern/chruby
source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh                       # Homebrew
source $(brew --prefix)/opt/chruby/share/chruby/auto.sh                         # Homebrew
# source /opt/local/share/chruby/chruby.sh                                      # MacPorts
# source /opt/local/share/chruby/auto.sh                                        # MacPorts
chruby 4.0.6
