# Mac-like keyboard shortcuts for a windows keyboard
# Place in /etc/keyd/default.conf

[ids]
*

[main]
# Left alt triggers the "cmd" layer
leftalt = layer(cmd)

# Swap meta/alt (not really needed?)
# leftmeta = alt    

[meta]
# Disable win+tab so it doesn't conflict with app_switch_state
tab = noop

# Option text navigation and selection
right = C-right
left = C-left
backspace = C-backspace

[cmd:C]
# Essential shortcuts
c = C-insert        # Copy
v = S-insert        # Paste
x = S-delete        # Cut
q = A-f4            # Quit

# Switch directly to an open tab in app
1 = A-1
2 = A-2
3 = A-3
4 = A-4
5 = A-5
6 = A-6
7 = A-7
8 = A-8
9 = A-9

# Text navigation line
left = home
right = end
up = C-home
down = C-end

# As soon as tab is pressed (but not yet released), we switch to the
# "app_switch_state" and send a 'M-tab' key tap before entering it
tab = swapm(app_switch_state, M-tab)

# Switch to next window in the application group using default binding (alt+f6)
` = A-f6

[app_switch_state:M]
# Switch to application
tab = M-tab
right = M-tab
left = M-S-tab
